services:

  server:
    container_name: server
    image: server:1.0
    networks:
    - _network
    build:
      context: srcs/server
      dockerfile: Dockerfile
    env_file:
    - .env
    restart: unless-stopped
    expose:
    - "9001"

  client:
    container_name: client
    image: client:1.0
    networks:
    - _network
    build:
      context: srcs/client
      dockerfile: Dockerfile
    depends_on:
    - server
    restart: unless-stopped
    ports:
    - "8080:8080"

  # database:
  #   container_name: database
  #   image: postgres:16
  #   networks:
  #   - _network
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - pgdata:/var/lib/pgsql/data
  #     - ./srcs/database/init:/docker-entrypoint-initdb.d
  #   restart: unless-stopped
  #   ports:
  #   - "5432:5432"

networks:
  _network:
    name: "_network"
    driver: "bridge"

volumes:
  pgdata:
    driver: local